services:
  mina:
    image: ${MINA}
    container_name: coordinator
    ports:
      - "0.0.0.0:8302:8302"
      - "0.0.0.0:8301:8301"
      - "127.0.0.1:3085:3085"
      - "0.0.0.0:3089:3089"
    restart: always
    env_file:
      - $HOME/mina-testworld-coordinator/.env
    environment: 
      MINA_LIBP2P_PASS: ${MINA_LIBP2P_PASS}
      RAYON_NUM_THREADS: ${RAYON_NUM_THREADS_COORD}
      MINA_CLIENT_TRUSTLIST: ${WORKER_IP}
    volumes:
      - "${CONFIG_DIRECTORY}:/root/.mina-config"
      - "${KEYS_PATH}:/root/keys:ro"
    command: >
      daemon
        --peer-list-url ${PEER_LIST}
        --libp2p-keypair ${LIBP2P_KEYPATH}
        --external-ip ${EXTERNAL_IP}
        --config-directory ${CONFIG_DIRECTORY}
        --run-snark-coordinator ${COORDINATOR_KEY}
        --snark-worker-fee ${FEE}
        --work-selection ${WORK_SELECTION}
        --enable-peer-exchange true
        --max-connections 200
        --file-log-rotations 500
        --log-snark-work-gossip true
        --insecure-rest-server
        --log-level Info
        --file-log-level Debug
