version: "3.3"

services:
  mina-snark-worker-1:
    image: ${MINA}
    container_name: worker-1
    env_file:
      - $HOME/mina-testworld-coordinator/.env
    environment: 
      RAYON_NUM_THREADS_WORKER: ${RAYON_NUM_THREADS_WORKER}
    command: >
      internal snark-worker
        --daemon-address ${COORDINATOR_IP}:8301
        --proof-level full
        --shutdown-on-disconnect false

  mina-snark-worker-2:
    image: ${MINA}
    container_name: worker-2
    env_file:
      - $HOME/mina-testworld-coordinator/.env
    environment: 
      RAYON_NUM_THREADS_WORKER: ${RAYON_NUM_THREADS_WORKER}
    command: >
      internal snark-worker
        --daemon-address ${COORDINATOR_IP}:8301
        --proof-level full
        --shutdown-on-disconnect false

  mina-snark-worker-3:
    image: ${MINA}
    container_name: worker-3
    env_file:
      - $HOME/mina-testworld-coordinator/.env
    environment: 
      RAYON_NUM_THREADS_WORKER: ${RAYON_NUM_THREADS_WORKER}
    command: >
      internal snark-worker
        --daemon-address ${COORDINATOR_IP}:8301
        --proof-level full
        --shutdown-on-disconnect false
